/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author glaubermello
 */



public class Sistema extends javax.swing.JFrame {

    /**
     * Creates new form Sistema
     */
    public Sistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        estOrigem = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        estDestino = new javax.swing.JComboBox();
        Buscar = new javax.swing.JButton();
        resultado = new javax.swing.JTextField();
        Resultado = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        estOrigem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14" }));

        jLabel1.setText("Origem");

        jLabel2.setText("Destino");

        jLabel3.setText("Sistema de Metrô");

        estDestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14" }));
        estDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estDestinoActionPerformed(evt);
            }
        });

        Buscar.setText("A*");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Resultado.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(35, 35, 35)
                                .addComponent(estOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(estDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Resultado)
                        .addGap(18, 18, 18)
                        .addComponent(resultado)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(estDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Resultado))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    
    
    
    
    private void estDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estDestinoActionPerformed
        // TODO add your handling code here:s
    }//GEN-LAST:event_estDestinoActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        
         // Tabela da distância em linha reta
        double distLR[][] = {{0,11,20,27,40,43,39,28,18,10,18,30,30,32},
            {11,0,9,16,29,32,28,19,11,4,17,23,21,24},{20,9,0,7,20,22,19,15,10,11,21,21,13,18},
            {27,16,7,0,13,16,12,13,13,18,26,21,11,17},{40,29,20,13,0,3,2,21,25,31,38,27,16,20},
            {43,32,22,16,3,0,4,23,28,33,41,30,17,20},{39,28,19,12,2,4,0,22,25,29,38,28,13,17},
            {28,19,15,13,21,23,22,0,9,22,18,7,25,30},{18,11,10,13,25,28,25,9,0,13,12,12,23,28},
            {10,4,11,18,31,33,29,22,13,0,20,27,20,23},{18,17,21,26,38,41,38,18,12,20,0,15,35,39},
            {30,23,21,21,27,30,28,7,12,27,15,0,31,37},{30,21,13,11,16,17,13,25,23,20,35,31,0,5},
            {32,24,18,17,20,20,17,30,28,23,39,37,5,0}};
        
        // Tabela da distância entre as estações vizinhas
        // Onde -1 indica que não há adjacência com aquela estação
        double distE[][] = {{-1,10,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
            {10,-1,8.5,-1,-1,-1,-1,-1,10.3,3.5,-1,-1,-1,-1},{-1,8.5,-1,6.3,-1,-1,-1,-1,9.4,-1,-1,-1,-1,18.7},
            {-1,-1,6.3,-1,13,-1,-1,15.3,-1,-1,-1,-1,12.8,-1},{-1,-1,-1,13,-1,3,2.4,30,-1,-1,-1,-1,-1,-1},
            {-1,-1,-1,-1,3,-1,-1,-1,-1,-1,-1,-1,-1,-1},{-1,-1,-1,-1,2.4,-1,-1,-1,-1,-1,-1,-1,-1,-1},
            {-1,-1,-1,15.3,30,-1,-1,-1,9.6,-1,-1,6.4,-1,-1},{-1,10,9.4,-1,-1,-1,-1,9.6,-1,-1,12.2,-1,-1,-1},
            {-1,3.5,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},{-1,-1,-1,-1,-1,-1,-1,-1,12.2,-1,-1,-1,-1,-1},
            {-1,-1,18.7,12.8,-1,-1,-1,-1,-1,-1,-1,-1,-1,5.1},{-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,5.1,-1}};
        
        double menor=0;
        int k=0,j=0;
        
        
        
    int origem = Integer.parseInt((String)estOrigem.getSelectedItem());
    int destino = Integer.parseInt((String)estDestino.getSelectedItem()); 
    int l = destino;
    
    System.out.println(origem);
    
    do{
        
        
        for(int i=0;i<14;i++){
        if(distE[origem - 1][i] != -1){
            
            double custoTotal = distE[origem - 1][i] + distLR[i][destino-1];
            //System.out.println(custoTotal);
            
            if(k==0){
                menor = custoTotal;
                l= i;
                k++;
            }else{
                if(custoTotal < menor){
                    menor = custoTotal;
                    l = i;
                }      
            }
                    
        }
    }
    
        origem = ++l;
        System.out.println(l);
        
           
    }while(l!=destino);
    
 
    
    
    }//GEN-LAST:event_BuscarActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel Resultado;
    private javax.swing.JComboBox estDestino;
    private javax.swing.JComboBox estOrigem;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}

